// Use the following commands to build this.
// cl /EHsc PreD3Dcompile.cpp /MD /Fe:PreD3Dcompile.exe && PreD3Dcompile.exe && del PreD3Dcompile.obj && del PreD3Dcompile.exe
#include <fstream>
#include <iomanip>
#include <d3dcompiler.h>

#pragma comment(lib, "d3dcompiler.lib")

constexpr const char* g_vsCode = R"(
struct VS_IN {
    float2 pos : POSITION;
    float2 uv  : TEXCOORD0;
};

struct PS_IN {
    float4 pos : SV_POSITION;
    float2 uv  : TEXCOORD0;
};

PS_IN main(VS_IN input) {
    PS_IN o;
    o.pos = float4(input.pos, 0, 1);
    o.uv = input.uv;
    return o;
}
)";

constexpr const char* g_psCode = R"(
Texture2D tex0 : register(t0);
SamplerState samp0 : register(s0);

cbuffer Constants : register(b0) {
    float opacity;
};

struct PS_IN {
    float4 pos : SV_POSITION;
    float2 uv  : TEXCOORD0;
};

float4 main(PS_IN input) : SV_TARGET {
    float4 c = tex0.Sample(samp0, input.uv);
    c.a *= opacity;
    return c;
}
)";

static void WriteBlobArray(
    std::ofstream& output,
    const char* name,
    ID3DBlob* blob)
{
    const BYTE* data = static_cast<const BYTE*>(blob->GetBufferPointer());

    size_t size = blob->GetBufferSize();

    output << "constexpr unsigned char " << name << "[] = {\n";

    for (size_t i = 0; i < size; ++i)
    {
        if (i % 16 == 0)
        {
            output << "    ";
        }

        output
            << "0x"
            << std::hex
            << std::uppercase
            << std::setw(2)
            << std::setfill('0')
            << static_cast<int>(data[i]);

        if (i + 1 != size)
        {
            output << ", ";
        }

        if (i % 16 == 15)
        {
            output << '\n';
        }
    }

    if (size % 16 != 0)
    {
        output << '\n';
    }

    output << "};\n\n";
}

int main()
{
    ID3DBlob* vsBlob = nullptr;
    ID3DBlob* psBlob = nullptr;
    ID3DBlob* errorBlob = nullptr;

    HRESULT hr;

    hr = D3DCompile(
        g_vsCode,
        strlen(g_vsCode),
        nullptr,
        nullptr,
        nullptr,
        "main",
        "vs_4_0",
        D3DCOMPILE_OPTIMIZATION_LEVEL3 | D3DCOMPILE_WARNINGS_ARE_ERRORS,
        0,
        &vsBlob,
        &errorBlob);

    if (FAILED(hr))
    {
        if (errorBlob)
        {
            fprintf(
                stderr,
                "VS compile error:\n%s\n",
                (const char*)errorBlob->GetBufferPointer());

            errorBlob->Release();
        }

        return 1;
    }

    hr = D3DCompile(
        g_psCode,
        strlen(g_psCode),
        nullptr,
        nullptr,
        nullptr,
        "main",
        "ps_4_0",
        D3DCOMPILE_OPTIMIZATION_LEVEL3,
        0,
        &psBlob,
        &errorBlob);

    if (FAILED(hr))
    {
        if (errorBlob)
        {
            fprintf(
                stderr,
                "PS compile error:\n%s\n",
                (const char*)errorBlob->GetBufferPointer());

            errorBlob->Release();
        }

        vsBlob->Release();
        return 1;
    }

    std::ofstream output("PreCompiledBlob.h");

    output << "// Generated by:\n"
        "// cl /EHsc PreD3Dcompile.cpp /MD /Fe:PreD3Dcompile.exe && PreD3Dcompile.exe && del PreD3Dcompile.obj && del PreD3Dcompile.exe\n\n"
        
        "#pragma once\n"
        "#ifndef PRECOMPILEDBLOB_H\n"
        "#define PRECOMPILEDBLOB_H\n\n";

    WriteBlobArray(output, "g_vsBlobRawdata", vsBlob);
    WriteBlobArray(output, "g_psBlobRawdata", psBlob);

    output << "#endif // PRECOMPILEDBLOB_H\n";

    vsBlob->Release();
    psBlob->Release();

    return 0;
}